config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :sessions do
    collection do
      delete :signout 
    end
  end

  match '/home' => 'static_pages#home', :via => :get

  match '/' => 'static_pages#home', :via => :get, :as => :rrrr

  match '/help' => 'static_pages#help', :via => :get

  match '/about', to: 'static_pages#about', via: :get

  match '/signup', to: 'users#new', via: :get

  match '/signin', to: 'sessions#new', via: :get

end

app/models/groups.rb
class Groups < ActiveRecord::Base
	attr_accessible :group_id, :title

	validates :title, :presence => :true, :uniqueness => :true

	has_many :user_groups, dependent: :destroy
end

app/models/periodic_tasks.rb
class PeriodicTasks < ActiveRecord::Base
	attr_accessible :title, 
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token
#	after_save :clear_password

	attr_accessible :name, :email, :password, :password_confirmation	
	# has_secure_password
	validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :email, :presence => true, :uniqueness => true
	validates_format_of :email, :with => /@/	
	validates :password, :presence => true, :length => { :in => 6..20 }
	validates :password, :confirmation => true

	has_many :user_groups, dependent: :destroy
	
	def isEmail(str)
  		return str.match(/[a-zA-Z0-9._%]@(?:[a-zA-Z0-9]\.)[a-zA-Z]{2,4}/)
	end

	def self.authenticate(name_or_email="", login_password="")
		if isEmail(name_or_email)
			user = User.find_by_email(name_or_email)
		else
			user = User.find_by_name(name_or_email)
		end

		if user && user.password == login_password
			return user
		else
			return false
		end
	end

	def self.authenticate(login_password="")
		if self.password == login_password
			return true
		else
			return false
		end
	end

	def isMember?(group_id)
		##Verify if the person is a member of the group?
	end

	private
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end

end

app/models/user_groups.rb
class UserGroups < ActiveRecord::Base
	attr_accessible :user_id, :group_id

	belongs_to :user
	belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def handle_unverified_request
  	sign_out
  	super
  end
  
	def save_login_state
		if session[:user_id]
			redirect_to(:controller => 'sessions', :action => 'home')
		return false
		else
			return true
		end
	end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def create_group(group_title="")		
		myGroup = groups.new(group_title)
		if myGroup.save			
			user_group_entry = user_groups.new(group_id=myGroup.id,user_id=self.id)
			if user_group_entry.save
				flash[:success] = "You successfully created a group named ".to_s + group_title
			else
				## Support an error message.
			end
		else
			## Support an error message.
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	before_filter :save_login_state, :only => [:index, :signin, :signup]

	def new

	end

	def create
		user = User.find_by_name(params[:session][:email].downcase)
		auth = (user.password == params[:session][:password])

		if user && auth
			sign_in user
			flash[:success] = "Welcome to Work Share app."
			redirect_to user
		else
			flash[:error] = 'Invalid id/password combination.'
			flash[:color] = "Invalid"
			render 'new'
		end
	end

	def signout
		sign_out
		redirect_to signin_path
	end

	def newGroup
		create_group(group_title)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:show]

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(params[:user])  	
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Work Share app!"
  		redirect_to @user      
  	else
  		render 'new'
  	end
  end

  def signed_in_user
    redirect_to signin_url, notice: "Please Sign in." unless signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Welcome to Work Share app."
		if page_title.empty?
			base_title		
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
		puts "XXXXXXXXXXXXXXXXXXXXXXXX"
		puts user.remember_token
		puts user
		puts "XXXXXXXXXXXXXXXXXXXXXXXX"
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#'  %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Work Share app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",  home_path   %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li id='fat-menu' class='dropdown'>
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                Account <b class='caret'> </b>
              </a>
              <li>
                <%= link_to "Sign Out", signout_sessions_path, method: 'delete' %>
              </li>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", '#' %> </li>
                <li><%= link_to "Settings", '#' %> </l1>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign Out", signout_sessions_path, method: 'delete' %>
                </li>
              </ul>
            </li>
          <% else %>
          <li><%= link_to "Sign in",  signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
  	<%= render 'layouts/header' %>    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %> </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%=pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li> *<%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Home') %>
<html>
  <head>
  <title><%= full_title(yield(:title)) %></title>  
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Sample App</h1>
    <p>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>

    <div class="row">
	 	<div class="span6 offset3">
	    	<%= form_for(:groups, url: '') do |f| %>

	      	<%= f.label :group_title %>
	      	<%= f.text_field :group_title %>

	    	<%= f.submit "Create group", class: "btn btn-large btn-primary" %>	    
			<% end %>
		</div>
	</div>

    </section>
  </aside>
</div>